---
- name: Running pre deploy tasks
  block: 
    - include_tasks: hooks/pre_deploy_larapaper.yaml

- ansible.builtin.include_role:
    name: stack_generic
  vars:
    stack_name: smarthome

- name: Upload Home Assistant Traefik router
  ansible.builtin.template: 
    src: templates/traefik/home-assistant.toml.j2
    # TODO: This should be a variable in the stack_generic role, but for now we hardcode it here
    dest: /opt/stacks/network/config/traefik/dynamic/home-assistant.toml
    owner: "{{ ansible_user }}"
    group: docker
    mode: '0644'
  when: create_home_assistant_router

