---
- name: Ensure Komodo install directory exists
  ansible.builtin.file:
    path: "{{ install_dir }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Deploy Komodo Periphery with Docker Compose
  ansible.builtin.copy:
    src: compose.yaml
    dest: "{{ install_dir }}/compose.yaml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

- name: Deploy Komodo Periphery compose env file
  ansible.builtin.template:
    src: compose.env.j2
    dest: "{{ install_dir }}/.env"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'
  no_log: true

- name: Start Komodo Periphery with Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ install_dir }}"
    state: present
    recreate: "always"
    remove_orphans: true
