# Dropping this file in /syncs will _not_ work. Bootstrapping still needs either 
# a script to call the API or manual creation of the repo and resource sync. 
# This file is only used as a template for the configuration of the repo and 
# resource sync, which will be created manually for now.
# See: https://github.com/moghtech/komodo/issues/799
[[repo]]
name = "homelab"

[repo.config]
server = "komodo-01"
git_account = "NiekKeijzer"
repo = "niekkeijzer/homelab"
# Temporarily using a feature branch to test the sync functionality, will switch to main once it's working properly.
# TODO: Switch to main branch once the sync functionality is verified to be working properly.
branch = "feat/komodo"

[[resource_sync]]
name = "homelab"
description = "Syncs all Komodo resources declared in komodo/ of this repo."

[resource_sync.config]
linked_repo = "test"
resource_path = ["komodo/"]
include_variables = true
include_user_groups = true
