---
- hosts: docker 
  pre_tasks:
    - name: Create external infra network
      community.docker.docker_network:
        name: infra
        driver: bridge
        state: present
  roles:
    - role: docker_stack
      stack_name: infra 
  tags: 
    - infra

- hosts: docker 
  pre_tasks:
    - name: Create external proxy network
      community.docker.docker_network:
        name: proxy
        driver: bridge
        state: present
  roles:
    - role: docker_stack
      stack_name: network
  tags: 
    - network

- hosts: docker
  pre_tasks:
    - name: Fix Grafana data directory permissions 
      ansible.builtin.file: 
        path: "{{ stack_root }}/monitoring/data/grafana"
        owner: 1000
        state: directory
        mode: '0755'
        recurse: true

    - name: Create victoria metrics file_sd containing Ansible inventory
      ansible.builtin.template:
        src: ansible_targets.json.j2
        dest: "{{ playbook_dir }}/../stacks/monitoring/config/vmagent/file_sd/ansible_targets.json"
      delegate_to: localhost
      run_once: true
      become: false

    - name: Create victoria metrics file_sd containing non-docker services with metrics endpoints 
      ansible.builtin.template:
        src: service_targets.json.j2
        dest: "{{ playbook_dir }}/../stacks/monitoring/config/vmagent/file_sd/service_targets.json"
      delegate_to: localhost
      run_once: true
      become: false
      vars:
        services: 
          - name: coredns
            host: dns-01
            port: 9153

  roles:
    - role: docker_stack
      stack_name: monitoring
  tags: 
    - monitoring

- hosts: docker
  pre_tasks: 
    - name: Create security secrets
      include_role:
        name: fnox_secret
      vars:
        secret_name: "{{ item.name }}"
        secret_value: "{{ item.value }}"
      with_items: 
        - name: SECURITY_AUTHENTIK_SECRET_KEY
          value: null
        - name: SECURITY_AUTHENTIK_POSTGRES_PASSWORD
          value: null
        - name: SECURITY_AUTHENTIK_POSTGRES_DB
          value: "authentik"
        - name: SECURITY_AUTHENTIK_POSTGRES_USER
          value: "authentik"
      no_log: true

    - name: Create PostgreSQL user and database if not exists
      include_role:
        name: docker_postgres_user
      vars:
        pg_user: "{{ lookup('env', 'SECURITY_AUTHENTIK_POSTGRES_USER') }}"
        pg_password: "{{ lookup('env', 'SECURITY_AUTHENTIK_POSTGRES_PASSWORD') }}"
        pg_db: "{{ lookup('env', 'SECURITY_AUTHENTIK_POSTGRES_DB') }}"
      # no_log: true



  roles:
    - role: docker_stack
      stack_name: security
  tags: 
    - security
    